spring:
  kafka:
    client-id: at-most-once-app
    listener:
      ack-mode: manual
    consumer:
      bootstrap-servers: localhost:9092
      enable:
        auto:
          commit: false
      auto-offset-reset: latest
      group-id: at-most-once-group

    producer:
      bootstrap-servers: localhost:9092
