spring:
  kafka:
    client-id: at-most-once-app

    consumer:
      bootstrap-servers: localhost:9092
      group-id: at-most-once-group

    producer:
      bootstrap-servers: localhost:9092
      delivery:
        timeout:
          ms:10
      retries: 0
      acks: 0
