spring:
  kafka:
    client-id: at-most-once-app

    consumer:
      enable:
        auto:
          commit: true
      auto:
        commit:
          interval:
            ms: 5
      auto-offset-reset: earliest
      group-id: at-least-once-group

    producer:
      bootstrap-servers: localhost:9092
